
services:
  restic-rest-server:
    image: restic/rest-server:latest
    container_name: restic-rest-server
    ports:
        # Change the standard port to 8888 because Portainer is also using it.
      - 8888:8000
    volumes:
      - /media/backup/restic-repo:/data
    restart: unless-stopped

# After deployment a user needs to be created:
# docker exec -it restic-rest-server create_user restic restic
