services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /home/ethos/docker/beszel/beszel_data:/beszel_data
      - /home/ethos/docker/beszel/beszel_socket:/beszel_socket
