services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/ethos/docker/beszel/beszel_data:/beszel_data
      - /home/ethos/docker/beszel/beszel_socket:/beszel_socket
