services:
  # https://hub.docker.com/r/nodered/node-red
  node-red-dev:
    restart: unless-stopped
    container_name: node-red-dev
    image: nodered/node-red:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/ethos/docker/node-red-dev:/data
    ports:
      - "1880:1880"

  # Auto reload on change:    
  # while inotifywait -e close_write /home/ethos/docker/node-red-dev/lib/hello-world/hello-world.js; 
  # do   
  #   echo "Change detected, restarting Node-RED container...";   
  #   docker restart node-red-dev; 
  # done
